### ISSUE TITLE
lightbox starts open and wont close

### ISSUE THREAD

**Issue by gamarobert** [theanam/react-awesome-lightbox#1]
hey i like this project! and maybe its my own misunderstanding but the example of usage just has the props of image and title being passed. do i need to pass anything else for the single image lightbox to have initial state as closed and a function to handle the closing of lightbox?

**Comment by theanam** [comment]
Hello, this component leaves the freedom of showing/hiding on the developer to ensure full freedom. If you just need simple showing/hidnig try creating a state variable for example: lightbox_shown and initially set it to false. In your JSX, use the lightbox like this:

{lightbox_shown?<Lightbox image=“image url”/>:null}
