### ISSUE TITLE
Can't exit when hitting X

### ISSUE THREAD

**Issue by ttgiang** [theanam/react-awesome-lightbox#2]
Great code. Thank you for sharing. I'm working with React and have included the code successfully. The only issue is the gallery does not close when hitting the X. The other buttons work. Rotate, zoom as such. Just X won't work. Please advise.

**Comment by theanam** [comment]
Hello, 
The keyboard shortcut for triggering the close function is Esc. If you want to use the X key, I guess initiating an event handler on the top level component and running the close function there would work :)

**Comment by theanam** [comment]
Sorry I probably got your issue wrong. The show hide of the lightbox is completely under the developer’s control. 

Try creating a state variable, and show the lightbox only when the state variable is true. E.g: {this.state.showLightbox?<Ligjtbox onClose={()=>this.setState({showLightbox:false})}/>:null}
