### ISSUE TITLE
Dependency issue with react v17+ and npm v7+

### ISSUE THREAD

**Issue by bilalahmed24** [theanam/react-awesome-lightbox#5]
npm v7+ wont allow package to be installed with react v17+ due to conflicting peer dependency.

Needs update.

**Comment by samrocksc** [comment]
Hello @bilalahmed24 I noticed there was not a PR for this; however, this commit looks to have solved the issue with moving this to version 17

https://github.com/theanam/react-awesome-lightbox/commit/6a0ce16936e7e016ff27c882a03f2fdac471faac

**Comment by samrocksc** [comment]
@romgain can this issue be closed?

**Comment by romgain** [comment]
Yes, this got fixed in #6 😊

**Comment by bilalahmed24** [comment]
@samrocksc surely, the issue is resolved. :)
